### ISSUE TITLE
Specified functions are actually macros

### ISSUE THREAD

**Issue by poldy** [ruricolist/core-lisp#3]
For example:

```
* (in-package :core-lisp-user)
#<COMMON-LISP:PACKAGE "CORE-LISP-USER">
* (macroexpand '(+ 2 2))
(COMMON-LISP:+ 2 2)
COMMON-LISP:T
* (apply #'+ '(1 2))

debugger invoked on a COMMON-LISP:UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {10005B05B3}>:
  The function CORE-LISP:+ is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

((COMMON-LISP:LAMBDA (&REST SB-IMPL::ARGS) :IN SB-C::INSTALL-GUARD-FUNCTION))
0] 0
* (apply #'cl:+ '(1 2))
3
* 
```

According to [the hyperdraft](http://minejima.jp/ISLispHyperDraft/islisp-v23.html#f_plus) `+` must be a function.

I'd say this breaks a huge amount of idiomatic Lisp code. The root cause is may be related to [import-function](https://github.com/ruricolist/core-lisp/blob/master/core-lisp-boot.lisp#L240), but I'm just guessing.

**Comment by ruricolist** [comment]
This happens because, in the default readtable, `#'+` expands to `(cl:function x)`, and Core Lisp requires you to use `(core-lisp:function x)` instead. So you either have to write it out:

    (apply (function +) '(1 2))

Or switch to the provided readtable, `core-lisp:core-lisp` (using [named-readtables](https://github.com/melisgl/named-readtables).)

**Comment by poldy** [comment]
Thanks, your suggestion to use `(function x)` worked. Now I have to read up on named-readtables :-)
